name: CI with Coveralls

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm install
      
      - name: Build the project
        run: npm run build --if-present

      - name: Set executable permission for Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests and generate coverage
        run: npx jest --coverage

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true                            